### ISSUE TITLE
repo rename

### ISSUE THREAD

**Issue by samhere17** [wrappid/vscode-extension#12]
- [X] I think the repo should be named "vscode-extension" instead of "wrappidextension".
I am suggesting this change only for the codename.

The name visible in the marketplace also needs to be worked on.
We should try to name it something interesting.

I suggest "Wrappid Magic".

Please share your recommendations.

**Comment by irkfaisal** [comment]
I am suggesting a simple name 'Wrappid Snippets'

**Comment by Swrnv-qc** [comment]
> I am suggesting a simple name 'Wrappid Snippets'

But there will be more functionalities rather than just giving snippet completions.

I suggest the name "Wrappid IntelliSense"

**Comment by samhere17** [comment]
The repo has been renamed to **vscode-extension**; closing the issue.

Regarding the name visible in the marketplace, we now have a discussion:
https://github.com/orgs/wrappid/discussions/18
